Bump dependencies
marcelpinto/permissions-ktx pull request #8
Opened 2021-05-10 05:45 UTC by erikeelde

2021-05-10 05:50 UTC, erikeelde commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.0-bin.zip
This change had some implications for publishing for me - the gradle publishing plugins have changed. I think the bintray plugin will work with it. But might be nice to test it out first.

2021-06-06 05:47 UTC, marcelpinto requested changes
Thanks for doing this. Just a minor comment.

2021-06-06 05:47 UTC, marcelpinto commented on lib/build.gradle.kts
> -        versionCode = 7
What's the reason of removing the versionCode + Name?

2021-06-06 05:47 UTC, marcelpinto commented on lib/build.gradle.kts
> +    from(android.sourceSets.getByName("main").java.srcDirs())
note, that this uses Kotlin Gradle files. Using the srcDirs directly is the normal kotlin practice

2021-06-06 06:04 UTC, marcelpinto commented on lib/build.gradle.kts
> +    from(android.sourceSets.getByName("main").java.srcDirs())
Oh I see that in the new version of gradle this changed.

2021-06-06 06:05 UTC, marcelpinto approved these changes

2021-06-06 06:06 UTC, merged